# Generated by Django 4.1.3 on 2022-11-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
