# Generated by Django 4.1.3 on 2022-11-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0003_alter_entry_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=256)),
                ("url", models.URLField()),
            ],
        ),
    ]
