# Generated by Django 4.1.3 on 2022-11-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0004_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
