# Generated by Django 4.1.3 on 2022-11-11 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0006_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="anger",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-5),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="fear",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-5),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="peace",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-5),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="power",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-5),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
