# Generated by Django 4.1.3 on 2022-11-17 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0007_entry_anger_entry_fear_entry_peace_entry_power"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("activity", models.CharField(max_length=64)),
                (
                    "time",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "activity_type",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mental_health_diary.activitytype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entry",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mental_health_diary.activity",
            ),
        ),
    ]
