# Generated by Django 4.1.3 on 2022-11-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0008_activitytype_activity_entry_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity", options={"verbose_name_plural": "Activities"},
        ),
    ]
