# Generated by Django 4.1.3 on 2022-11-20 14:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mental_health_diary", "0009_alter_activity_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity", old_name="activity_type", new_name="type",
        ),
        migrations.RemoveField(model_name="activity", name="time",),
        migrations.RemoveField(model_name="entry", name="activity",),
        migrations.CreateModel(
            name="ActivityEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "time",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "activity",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mental_health_diary.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Activity Entry",},
        ),
    ]
