# Generated by Django 4.1.3 on 2022-11-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0010_rename_activity_type_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mental_health_diary.activitytype",
            ),
        ),
    ]
