# Generated by Django 4.1.3 on 2022-11-20 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0011_alter_activity_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activityentry", old_name="user", new_name="creator",
        ),
        migrations.AddField(
            model_name="activityentry",
            name="date",
            field=models.DateField(default=datetime.date(2022, 11, 20)),
        ),
        migrations.AddField(
            model_name="activityentry",
            name="url",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
