# Generated by Django 4.1.3 on 2022-11-21 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mental_health_diary",
            "0012_rename_user_activityentry_creator_activityentry_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityentry", options={"verbose_name_plural": "Activity Entries"},
        ),
        migrations.AlterField(
            model_name="activityentry",
            name="date",
            field=models.DateField(default=datetime.date(2022, 11, 21)),
        ),
    ]
