# Generated by Django 4.1.3 on 2022-11-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0014_alter_activityentry_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityentry",
            name="activity",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mental_health_diary.activity",
            ),
        ),
    ]
