# Generated by Django 4.1.3 on 2022-11-23 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0015_alter_activityentry_activity"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="description",),
        migrations.AddField(
            model_name="entry",
            name="date",
            field=models.DateField(default=datetime.date(2022, 11, 23)),
        ),
        migrations.AlterField(
            model_name="activityentry",
            name="date",
            field=models.DateField(default=datetime.date(2022, 11, 23)),
        ),
    ]
