# Generated by Django 4.1.3 on 2022-11-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mental_health_diary", "0016_remove_article_description_entry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityentry",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mental_health_diary.activity",
            ),
        ),
    ]
